def loadData(client):

    db = client.db
    listado = db.listado

    #borramos la coleccion
    listado.remove()

    docs = [{
          "id": 1,
          "sexo": "Female",
          "nombre": "Dorothy",
          "apellido": "Nelson",
          "pais": "China"
        }, {
          "id": 2,
          "sexo": "Male",
          "nombre": "Donald",
          "apellido": "Clark",
          "pais": "China"
        }, {
          "id": 3,
          "sexo": "Female",
          "nombre": "Joan",
          "apellido": "Robertson",
          "pais": "France"
        }, {
          "id": 4,
          "sexo": "Female",
          "nombre": "Ann",
          "apellido": "Mitchell",
          "pais": "China"
        }, {
          "id": 5,
          "sexo": "Male",
          "nombre": "Justin",
          "apellido": "Kelly",
          "pais": "China"
        }, {
          "id": 6,
          "sexo": "Female",
          "nombre": "Doris",
          "apellido": "Chapman",
          "pais": "Ukraine"
        }, {
          "id": 7,
          "sexo": "Female",
          "nombre": "Nancy",
          "apellido": "Wallace",
          "pais": "Haiti"
        }, {
          "id": 8,
          "sexo": "Male",
          "nombre": "Johnny",
          "apellido": "Grant",
          "pais": "Argentina"
        }, {
          "id": 9,
          "sexo": "Male",
          "nombre": "Jesse",
          "apellido": "Harrison",
          "pais": "China"
        }, {
          "id": 10,
          "sexo": "Male",
          "nombre": "Roger",
          "apellido": "Bowman",
          "pais": "Russia"
        }, {
          "id": 11,
          "sexo": "Male",
          "nombre": "Michael",
          "apellido": "Barnes",
          "pais": "United States"
        }, {
          "id": 12,
          "sexo": "Female",
          "nombre": "Jacqueline",
          "apellido": "Russell",
          "pais": "Ukraine"
        }, {
          "id": 13,
          "sexo": "Male",
          "nombre": "Benjamin",
          "apellido": "Matthews",
          "pais": "Poland"
        }, {
          "id": 14,
          "sexo": "Female",
          "nombre": "Rose",
          "apellido": "Mitchell",
          "pais": "Indonesia"
        }, {
          "id": 15,
          "sexo": "Female",
          "nombre": "Joyce",
          "apellido": "Cook",
          "pais": "Sweden"
        }, {
          "id": 16,
          "sexo": "Male",
          "nombre": "Andrew",
          "apellido": "Scott",
          "pais": "Philippines"
        }, {
          "id": 17,
          "sexo": "Male",
          "nombre": "Wayne",
          "apellido": "Richardson",
          "pais": "Macedonia"
        }, {
          "id": 18,
          "sexo": "Female",
          "nombre": "Rebecca",
          "apellido": "Warren",
          "pais": "Japan"
        }, {
          "id": 19,
          "sexo": "Female",
          "nombre": "Cheryl",
          "apellido": "Morales",
          "pais": "Niger"
        }, {
          "id": 20,
          "sexo": "Male",
          "nombre": "Robert",
          "apellido": "Ray",
          "pais": "Pakistan"
        }, {
          "id": 21,
          "sexo": "Male",
          "nombre": "Billy",
          "apellido": "Roberts",
          "pais": "China"
        }, {
          "id": 22,
          "sexo": "Male",
          "nombre": "Earl",
          "apellido": "Hernandez",
          "pais": "Thailand"
        }, {
          "id": 23,
          "sexo": "Female",
          "nombre": "Ashley",
          "apellido": "Jordan",
          "pais": "Indonesia"
        }, {
          "id": 24,
          "sexo": "Female",
          "nombre": "Carolyn",
          "apellido": "Richardson",
          "pais": "Serbia"
        }, {
          "id": 25,
          "sexo": "Female",
          "nombre": "Betty",
          "apellido": "Flores",
          "pais": "Poland"
        }, {
          "id": 26,
          "sexo": "Male",
          "nombre": "Mark",
          "apellido": "Long",
          "pais": "United States"
        }, {
          "id": 27,
          "sexo": "Female",
          "nombre": "Doris",
          "apellido": "Lewis",
          "pais": "Indonesia"
        }, {
          "id": 28,
          "sexo": "Female",
          "nombre": "Alice",
          "apellido": "Carpenter",
          "pais": "Democratic Republic of the Congo"
        }, {
          "id": 29,
          "sexo": "Male",
          "nombre": "Martin",
          "apellido": "Castillo",
          "pais": "Brazil"
        }, {
          "id": 30,
          "sexo": "Male",
          "nombre": "David",
          "apellido": "George",
          "pais": "Indonesia"
        }, {
          "id": 31,
          "sexo": "Male",
          "nombre": "Nicholas",
          "apellido": "Adams",
          "pais": "China"
        }, {
          "id": 32,
          "sexo": "Male",
          "nombre": "Carlos",
          "apellido": "Henry",
          "pais": "China"
        }, {
          "id": 33,
          "sexo": "Male",
          "nombre": "Juan",
          "apellido": "Dixon",
          "pais": "Russia"
        }, {
          "id": 34,
          "sexo": "Female",
          "nombre": "Marilyn",
          "apellido": "Mccoy",
          "pais": "Czech Republic"
        }, {
          "id": 35,
          "sexo": "Female",
          "nombre": "Phyllis",
          "apellido": "Jordan",
          "pais": "Morocco"
        }, {
          "id": 36,
          "sexo": "Female",
          "nombre": "Elizabeth",
          "apellido": "Reynolds",
          "pais": "Thailand"
        }, {
          "id": 37,
          "sexo": "Male",
          "nombre": "Juan",
          "apellido": "Medina",
          "pais": "Ukraine"
        }, {
          "id": 38,
          "sexo": "Female",
          "nombre": "Nicole",
          "apellido": "Fuller",
          "pais": "South Africa"
        }, {
          "id": 39,
          "sexo": "Female",
          "nombre": "Ruth",
          "apellido": "Griffin",
          "pais": "Botswana"
        }, {
          "id": 40,
          "sexo": "Female",
          "nombre": "Diana",
          "apellido": "Webb",
          "pais": "Indonesia"
        }, {
          "id": 41,
          "sexo": "Female",
          "nombre": "Virginia",
          "apellido": "West",
          "pais": "Vietnam"
        }, {
          "id": 42,
          "sexo": "Female",
          "nombre": "Jennifer",
          "apellido": "Lee",
          "pais": "Russia"
        }, {
          "id": 43,
          "sexo": "Female",
          "nombre": "Amanda",
          "apellido": "Cruz",
          "pais": "China"
        }, {
          "id": 44,
          "sexo": "Male",
          "nombre": "Antonio",
          "apellido": "Crawford",
          "pais": "South Korea"
        }, {
          "id": 45,
          "sexo": "Male",
          "nombre": "Richard",
          "apellido": "Perkins",
          "pais": "France"
        }, {
          "id": 46,
          "sexo": "Male",
          "nombre": "Harry",
          "apellido": "Pierce",
          "pais": "Japan"
        }, {
          "id": 47,
          "sexo": "Male",
          "nombre": "Samuel",
          "apellido": "Baker",
          "pais": "Mongolia"
        }, {
          "id": 48,
          "sexo": "Male",
          "nombre": "Carl",
          "apellido": "Barnes",
          "pais": "China"
        }, {
          "id": 49,
          "sexo": "Male",
          "nombre": "Paul",
          "apellido": "Foster",
          "pais": "Brazil"
        }, {
          "id": 50,
          "sexo": "Male",
          "nombre": "Howard",
          "apellido": "Williamson",
          "pais": "Venezuela"
        }]

    listado.insert_many(docs)